// <auto-generated />
using System;
using Admin.NET.EntityFramework.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Admin.NET.Database.Migrations.Migrations
{
    [DbContext(typeof(MultiTenantDbContext))]
    [Migration("20220508102114_v1.0.1")]
    partial class v101
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Admin.NET.Application.Entity.Deliverables", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("Id主键");

                    b.Property<string>("Acceptance")
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("上传验收单");

                    b.Property<DateTimeOffset?>("CreatedTime")
                        .HasColumnType("datetimeoffset")
                        .HasComment("创建时间");

                    b.Property<long?>("CreatedUserId")
                        .HasColumnType("bigint")
                        .HasComment("创建者Id");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("创建者名称");

                    b.Property<string>("Deliver")
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("上传交付物");

                    b.Property<string>("Enterprise")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasComment("所属企业");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasComment("创客姓名");

                    b.Property<string>("IdCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasComment("身份证号");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("软删除标记");

                    b.Property<DateTimeOffset>("Issue")
                        .HasColumnType("datetimeoffset")
                        .HasComment("当前月份");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasComment("任务");

                    b.Property<long>("State")
                        .HasColumnType("bigint")
                        .HasComment("状态");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetimeoffset")
                        .HasComment("更新时间");

                    b.Property<long?>("UpdatedUserId")
                        .HasColumnType("bigint")
                        .HasComment("修改者Id");

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("修改者名称");

                    b.HasKey("Id");

                    b.ToTable("Deliverables");

                    b.HasComment("交付物管理表");
                });

            modelBuilder.Entity("Furion.Extras.Admin.NET.SysTenant", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("Id主键");

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("管理员名称");

                    b.Property<string>("Connection")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("数据库连接");

                    b.Property<DateTimeOffset?>("CreatedTime")
                        .HasColumnType("datetimeoffset")
                        .HasComment("创建时间");

                    b.Property<long?>("CreatedUserId")
                        .HasColumnType("bigint")
                        .HasComment("创建者Id");

                    b.Property<string>("CreatedUserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("创建者名称");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("电子邮箱");

                    b.Property<string>("Host")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("主机");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("软删除标记");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("公司名称");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("电话");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("备注");

                    b.Property<string>("Schema")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("架构");

                    b.Property<DateTimeOffset?>("UpdatedTime")
                        .HasColumnType("datetimeoffset")
                        .HasComment("更新时间");

                    b.Property<long?>("UpdatedUserId")
                        .HasColumnType("bigint")
                        .HasComment("修改者Id");

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("修改者名称");

                    b.HasKey("Id");

                    b.ToTable("sys_tenant");

                    b.HasComment("租户表");

                    b.HasData(
                        new
                        {
                            Id = 142307070918780L,
                            AdminName = "SuperAdmin",
                            Connection = "",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Email = "515096995@163.com",
                            Host = "",
                            IsDeleted = false,
                            Name = "平台开发",
                            Phone = "18020030720"
                        },
                        new
                        {
                            Id = 142307070918781L,
                            AdminName = "Admin",
                            Connection = "",
                            CreatedTime = new DateTimeOffset(new DateTime(2021, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            Email = "zuohuaijun@163.com",
                            Host = "",
                            IsDeleted = false,
                            Name = "公司1租户",
                            Phone = "18020030720"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
