/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/Admin.NET/'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RoleOptionOutput } from './role-option-output';
/**
 * 角色已分配可分配输出参数
 * @export
 * @interface GrantRoleOutput
 */
export interface GrantRoleOutput {
    /**
     * 以分配
     * @type {Array<RoleOptionOutput>}
     * @memberof GrantRoleOutput
     */
    granted?: Array<RoleOptionOutput> | null;
    /**
     * 可分配
     * @type {Array<RoleOptionOutput>}
     * @memberof GrantRoleOutput
     */
    available?: Array<RoleOptionOutput> | null;
}
