/* tslint:disable */
/* eslint-disable */
/**
 * 所有接口
 * 让 .NET 开发更简单、更通用、更流行。前后端分离架构(.NET6/Vue3)，开箱即用紧随前沿技术。<br/><a href='https://gitee.com/zuohuaijun/Admin.NET/'>https://gitee.com/zuohuaijun/Admin.NET</a>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 角色选项输出参数
 * @export
 * @interface RoleOptionOutput
 */
export interface RoleOptionOutput {
    /**
     * Id
     * @type {number}
     * @memberof RoleOptionOutput
     */
    id?: number;
    /**
     * 名称
     * @type {string}
     * @memberof RoleOptionOutput
     */
    name?: string | null;
    /**
     * 编码
     * @type {string}
     * @memberof RoleOptionOutput
     */
    code?: string | null;
    /**
     * 是否禁用
     * @type {boolean}
     * @memberof RoleOptionOutput
     */
    disabled?: boolean;
}
