/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 应用输出参数
 * @export
 * @interface SysAppOutput
 */
export interface SysAppOutput {
    /**
     * 主键Id
     * @type {number}
     * @memberof SysAppOutput
     */
    id?: number;
    /**
     * 名称
     * @type {string}
     * @memberof SysAppOutput
     */
    name?: string | null;
    /**
     * 图标
     * @type {string}
     * @memberof SysAppOutput
     */
    logo?: string | null;
    /**
     * 标题
     * @type {string}
     * @memberof SysAppOutput
     */
    title?: string | null;
    /**
     * 副标题
     * @type {string}
     * @memberof SysAppOutput
     */
    viceTitle?: string | null;
    /**
     * 副描述
     * @type {string}
     * @memberof SysAppOutput
     */
    viceDesc?: string | null;
    /**
     * 水印
     * @type {string}
     * @memberof SysAppOutput
     */
    watermark?: string | null;
    /**
     * 版权信息
     * @type {string}
     * @memberof SysAppOutput
     */
    copyright?: string | null;
    /**
     * ICP备案号
     * @type {string}
     * @memberof SysAppOutput
     */
    icp?: string | null;
    /**
     * 排序
     * @type {number}
     * @memberof SysAppOutput
     */
    orderNo?: number;
    /**
     * 备注
     * @type {string}
     * @memberof SysAppOutput
     */
    remark?: string | null;
    /**
     * 创建时间
     * @type {Date}
     * @memberof SysAppOutput
     */
    createTime?: Date | null;
    /**
     * 更新时间
     * @type {Date}
     * @memberof SysAppOutput
     */
    updateTime?: Date | null;
    /**
     * 创建者Id
     * @type {number}
     * @memberof SysAppOutput
     */
    createUserId?: number | null;
    /**
     * 创建者姓名
     * @type {string}
     * @memberof SysAppOutput
     */
    createUserName?: string | null;
    /**
     * 修改者Id
     * @type {number}
     * @memberof SysAppOutput
     */
    updateUserId?: number | null;
    /**
     * 修改者姓名
     * @type {string}
     * @memberof SysAppOutput
     */
    updateUserName?: string | null;
    /**
     * 软删除
     * @type {boolean}
     * @memberof SysAppOutput
     */
    isDelete?: boolean;
}
